### ISSUE TITLE
Filter import - Howto?

### ISSUE THREAD

**Issue by mike811** [HEnquist/camillagui#111]
Hello,

I got lost trying to import some REW filters…
When selecting:
Import config -> CamillaDSP Config -> Selecting REW.yml : … but nothing happens!?
When doing:
Import config -> EqAPO Config -> Selecting REW.yml -> „select what to import" -> mark file -> import -> Message is displayed: … REW.yml was successful 

But how to proceed? Where do I have to select these imported filters? They do not show up in filters nor in the pipeline selector.

REW.yml:

filters:
  L_340Hz_24dBoct_1:
    parameters:
      freq: 266.0
      gain: -15.5
      q: 1.0
      type: Peaking
    type: Biquad
  L_340Hz_24dBoct_2:
    parameters:
      freq: 278.0
      gain: 6.0
      q: 3.151
      type: Peaking
    type: Biquad
  L_340Hz_24dBoct_3:
    parameters:
      freq: 361.0
      gain: 6.0
      q: 1.464
      type: Peaking
    type: Biquad
  L_340Hz_24dBoct_4:
    parameters:
      freq: 1002.0
      gain: 6.0
      q: 1.026
      type: Peaking
    type: Biquad
  L_340Hz_24dBoct_5:
    parameters:
      freq: 1383.0
      gain: -8.6
      q: 1.161
      type: Peaking
    type: Biquad
  L_340Hz_24dBoct_6:
    parameters:
      freq: 2023.0
      gain: -1.7
      q: 5.149
      type: Peaking
    type: Biquad
  L_340Hz_24dBoct_7:
    parameters:
      freq: 2699.0
      gain: 3.7
      q: 3.007
      type: Peaking
    type: Biquad
  L_340Hz_24dBoct_8:
    parameters:
      freq: 3692.0
      gain: -5.2
      q: 1.028
      type: Peaking
    type: Biquad
  L_340Hz_24dBoct_9:
    parameters:
      freq: 4735.0
      gain: 6.0
      q: 4.444
      type: Peaking
    type: Biquad
  L_340Hz_24dBoct_10:
    parameters:
      freq: 5908.0
      gain: -4.9
      q: 3.103
      type: Peaking
    type: Biquad
  L_340Hz_24dBoct_11:
    parameters:
      freq: 7666.0
      gain: -2.5
      q: 3.062
      type: Peaking
    type: Biquad
  L_340Hz_24dBoct_12:
    parameters:
      freq: 10387.0
      gain: 1.0
      q: 1.041
      type: Peaking
    type: Biquad
  L_340Hz_24dBoct_13:
    parameters:
      freq: 14036.0
      gain: 2.7
      q: 2.286
      type: Peaking
    type: Biquad
  L_340Hz_24dBoct_14:
    parameters:
      freq: 17920.0
      gain: 4.9
      q: 2.107
      type: Peaking
    type: Biquad
  L_340Hz_24dBoct_15:
    parameters:
      freq: 18630.0
      gain: -16.3
      q: 1.0
      type: Peaking
    type: Biquad
pipeline:
  names:
  - L_340Hz_24dBoct_1
  - L_340Hz_24dBoct_2
  - L_340Hz_24dBoct_3
  - L_340Hz_24dBoct_4
  - L_340Hz_24dBoct_5
  - L_340Hz_24dBoct_6
  - L_340Hz_24dBoct_7
  - L_340Hz_24dBoct_8
  - L_340Hz_24dBoct_9
  - L_340Hz_24dBoct_10
  - L_340Hz_24dBoct_11
  - L_340Hz_24dBoct_12
  - L_340Hz_24dBoct_13
  - L_340Hz_24dBoct_14
  - L_340Hz_24dBoct_15
  type: Filter

**Comment by HEnquist** [comment]
What do you mean by "nothing happens"? After selecting the file you should get a list of filters with checkboxes for selecting what to import. You don't get that?

The EqualizerAPO import won't work for this file, I'll make sure it gives some meaningful error instead in the next version.

**Comment by mike811** [comment]
Hey,

not at my PC right now but I remember a black screen.
When checking with an older CamillaDsp config some selections did appear. So it seems that it is related to some missing parts in my REW.yml file.
Did you try with it at your setup? Did it here with MacOS: Chrome and Safari and also iPad with Safari.

Regards
Michael

**Comment by HEnquist** [comment]
I'll try it to see where things go wrong. Could you attach the config file? The indentation of Yaml gets messed up when you paste it as text here.

**Comment by mike811** [comment]
[
[REW.yml.zip](https://github.com/HEnquist/camillagui/files/15222762/REW.yml.zip)

**Comment by HEnquist** [comment]
Works without problems here, on Mac using safari.
Are you using the latest gui?

**Comment by mike811** [comment]
With safari 16.6.1 it does not work here.
I was mistaken: no black screen, just no change after selecting REW.yml.
Did empty browser cache but that did not help.
Installation from previous version via:

cd ~
cd camilladsp
mv camillagui camillagui_old
wget https://github.com/HEnquist/camillagui-backend/releases/download/v2.1.0/camillagui.zip -P ~/camilladsp/
unzip ~/camilladsp/camillagui.zip -d ~/camilladsp/camillagui
sudo service camillagui stop

When dry running and importing REW.yml I get this:
![IMG_6187](https://github.com/HEnquist/camillagui/assets/55871370/d65d871a-b097-455f-bd16-8ddb1efdc0c2)
Sorry for the screenshot but this was currently the fastest way…

**Comment by HEnquist** [comment]
Ok got it! You need v.2.1.1 of the backend, it has a fix for exactly this error.

**Comment by mike811** [comment]
Cool! That’s it. Thanks a lot.
