### ISSUE TITLE
Feature request: Channel naming

### ISSUE THREAD

**Issue by mike811** [HEnquist/camillagui#116]
Hello Henrik,

it would be very helpful having configureable names in front of channel bar graphs. There where currently only In and Out is written.
Like: 
L, R, C, LFE, etc. for inputs
and
L-W, L-T, LFE-1, LFE-2, etc. for outputs

Thanks again for this fabulous software!
![image](https://github.com/HEnquist/camillagui/assets/55871370/3d9edb97-d51a-4e62-9dc3-7c021815b9b1)

**Comment by HEnquist** [comment]
Related to https://github.com/HEnquist/camilladsp/issues/140

The short version is that I would like to add this but it will take some work to figure out the best way to do it.

**Comment by mike811** [comment]
Hi Henrik,
just saw you implemented the naming stuff. Very cool!
Could you make the pipeline overview zoomable (via mouse wheel)? On a small screen a large configuration is to tiny (with 2.1.0) even in compact view.

**Comment by HEnquist** [comment]
> Could you make the pipeline overview zoomable (via mouse wheel)? On a small screen a large configuration is to tiny (with 2.1.0) even in compact view.

Can you open a new issue for this? Preferably with a screenshot of how it looks when it's bad.

**Comment by mike811** [comment]
Naming got implemented I guess. 
Thanks a lot.
