### ISSUE TITLE
Zooming in pipeline view

### ISSUE THREAD

**Issue by mike811** [HEnquist/camillagui#121]
Hi Henrik,

like mentioned before, could you make the pipeline overview zoomable (via mouse wheel)? On a small screen a large configuration is to tiny (with 2.1.0) even in compact view.
(not at my camilladsp PC atm, but I did send you my quite large config via email some days ago)

Regards 
Michael

**Comment by HEnquist** [comment]
This was added here: https://github.com/HEnquist/camillagui/pull/117

**Comment by mike811** [comment]
Cool, thanks!
