### ISSUE TITLE
Duplication of state in React components

### ISSUE THREAD

**Issue by JWahle** [HEnquist/camillagui#20]
There is a lot of state duplication in the react components.
The React tutorial recommends to lift state up to the topmost component that needs to access the state and pass it down as props to child components. (see https://reactjs.org/docs/lifting-state-up.html)
The children would then use event handler passed down from the parent to modify the parent state directly.
Thus components like `Devices`, `Capture`, `Playback`, etc. would not need to have their own state - they would just have props and use event handlers to update the parent state directly.
This would greatly simplify the event handling when fields change.
I ran into several issues here already.
One was #17 and right now, when I tried to add the mute options to gain filters and mixers.

If you are okay with that, I would change the event handling of the tabs (devices, filters, mixers, pipeline) to follow this structure.
While I'm at it, I would probably migrate the code to TypeScript - it seems to me, you intended to do that anyway.
This will probably lead to some changes in the general component structure.
What do you think?

**Comment by HEnquist** [comment]
These are all good ideas! 

I would like to move to Typescript, but so far I only managed to rename index.js to index.tsx and do the minimum required changes.

The messy states are basically a leftover from when I started on this with zero experience of React. Would be great if that got some attention!

**Comment by JWahle** [comment]
Cool, then I'll see, how far I get.
I'll try to start to do this piece by piece, so you can have a look early on.

**Comment by JWahle** [comment]
This was solved by #24 #25 #28 #31.
