### ISSUE TITLE
Request batching?

### ISSUE THREAD

**Issue by JWahle** [HEnquist/camillagui#21]
Hi,
I just wanted to know, is there a specific reason to retrieve each CDSP parameter (capturesignalrms, playbacksignalrms, capturerate, rateadjust, ...) in a separate HTTP request?
When I have the Chrome/Firefox Dev tools open, this gets annoying quickly.
Would you mind, if I batched them into one JSON response?

**Comment by HEnquist** [comment]
That's a change I have been thinking about implementing, but didn't get to yet. So no I don't mind :)

**Comment by JWahle** [comment]
I pushed commits with this change to `develop` on the front and backend.
Everything should keep working as usual, except the `Volume` panel should only show up, when a CDSP instance is connected.
@HEnquist if you find anything, please reopen this issue, or create a new one.
