### ISSUE TITLE
Pipeline editor should allow reordering of steps

### ISSUE THREAD

**Issue by HEnquist** [HEnquist/camillagui#29]
Currently the only way to insert a step somewhere in the pipeline is to delete everything after the new step, and the recreate things in the right order. This is quite inconvenient. Each step should have arrow buttons to move it up and down in the list.

**Comment by JWahle** [comment]
I agree - the reworked pipeline tab will have this.
I also thought about adding drag'n'drop functionality for this - however I am not sure, how easy this can be implemented.

**Comment by JWahle** [comment]
I wonder, if this is also necessary for the filters.
Dither is the only filter, where order matters, right?
How about placing it automatically as last filter in the chain?

**Comment by HEnquist** [comment]
Would be neat to be able to drag them around, but not sure if it's worth the extra work. Depends on how much extra work it is of course, and if it's fun to do.

FIlters should probably also have rearrange buttons yes. It only matters for dither yes, but if you have many filters you might want to put them in some specific order to make it easier to see the correct ones are there.

Having Dither automatically sink to the bottom could be helpful. Then the question is if the gui should handle that or if CamillaDSP should rearrange the filters internally.

**Comment by JWahle** [comment]
You are right, that for better overview it is beneficial to be able to reorder filters manually.
I would have put dither at the end only, if there is no option to rearrange the filters.
So I think, there is no need to magically place dither at the end.
Those who know what it is, probably know where to put it :)

**Comment by HEnquist** [comment]
Yes I think you are right, the users of the Dither filter probably know what they are doing. So buttons to move the filters, and no automatic reordering is the way to go.

**Comment by JWahle** [comment]
Solved with #31
