### ISSUE TITLE
[gui-config.yml] hide_playback_device broken ?

### ISSUE THREAD

**Issue by bitkeeper** [HEnquist/camillagui#30]
@JWahle all settings in the gui-config.yml work, only the playback_device cannot be hidden anymore ?
Is this on purpose or due the refactoring ?

**Comment by JWahle** [comment]
I pushed a fix to the `develop` branch, please check it out.

**Comment by JWahle** [comment]
@HEnquist I brought develop up to master for this - I did not want to push directly to master.

**Comment by bitkeeper** [comment]
@JWahle I can confirm that commit 7460169bc69bf218df81ccbe1e300a31061dc46c fixed it.

**Comment by bitkeeper** [comment]
Btw nice to have the develop in place, much better then merging the different PR is. And the commit reference is back to a single repo.
