### ISSUE TITLE
Create new release of camillagui + camillagui-backend

### ISSUE THREAD

**Issue by JWahle** [HEnquist/camillagui#32]
@HEnquist can you please
1. review merge #31 into develop
2. maybe review the remaining commits in develop
3. merge develop into master
4. and then create a new release of both camillagui and camillagui-backend

**Comment by HEnquist** [comment]
I just merged to develop. Before merging to master and making the new release I want to give it a good test run, both on linux and windows. 
BTW I saw some preview screenshots of camillagui in moOde, and the white camillagui looks a bit out of place in the dark theme of moode. Should we try making it dark to match? I didn't have any particular reason for picking white when I started, just ended up that way.

**Comment by JWahle** [comment]
> I just merged to develop. Before merging to master and making the new release I want to give it a good test run, both on linux and windows.

Sounds reasonable.
