### ISSUE TITLE
GUI style Customization

### ISSUE THREAD

**Issue by JWahle** [HEnquist/camillagui#33]
...
BTW I saw some preview screenshots of camillagui in moOde, and the white camillagui looks a bit out of place in the dark theme of moode. Should we try making it dark to match? I didn't have any particular reason for picking white when I started, just ended up that way.

_Originally posted by @HEnquist in https://github.com/HEnquist/camillagui/issues/32#issuecomment-786317302_

**Comment by JWahle** [comment]
> Should we try making it dark to match?

I think, it would be really cool, if it matched better. I also thought about some way of allowing customization to the CamillaGUI style. This would be really cool to allow others to customize it, if they want to include it in some kind of software distribution - like moOde. Then the devs could make it fit their style exactly. For example, in moOde the UI accent color is user configurable - so a static styling will always be a little off.

I am not completely sure, how to implement it, though.
We could 
- provide a very basic css with a few classes to style basic text, option labels, headings, buttons and the grouping boxes (the "Box" component)
- or just add some configuration file with options for some colors.

What do you think?

**Comment by JWahle** [comment]
@HEnquist what's you opinion on this?

**Comment by HEnquist** [comment]
Sorry forgot this one. Customizable is good. I think editing a css to customize is ok. It's quite easy to change colors and such without really knowing how css works.

It would be great if it could be possible to somehow pick up the user setting of moOde. I haven't looked at how that could be achieved, maybe it gets unreasonably complicated.

**Comment by JWahle** [comment]
Was implemented in #36
