### ISSUE TITLE
Plotting for filters with variables in filename

### ISSUE THREAD

**Issue by JWahle** [HEnquist/camillagui#43]
Convolution filters with variables in filename ($samplerate$, $channels$) cannot be plotted individually and also break plotting of any filter pipeline step that contains them.

Optimally, I would like, that for filters with variables in filename :
- plotting for individual filters works
- plotting of pipeline steps, that include such filters, works
- it is possible, to plot each variant of the filter
  - possibly through a select field with all variants in the filter plot view
- validation should be implemented as in https://github.com/HEnquist/pycamilladsp-plot/issues/10

**Comment by HEnquist** [comment]
The plotter will need the absolute path to the filter coeff files, with the variables substituted. Probably the backend is the easiest place to handle that.

**Comment by HEnquist** [comment]
I fixed it now so that it works to plot filters with tokens. It's using the samplerate and number of channels from the devices section, I did not implement any option for quickly plotting other combinations.

**Comment by JWahle** [comment]
Works for me.
I'll leave this ticket open, until I implemented the rest.

**Comment by JWahle** [comment]
Hi @HEnquist,
I just pushed an implementation of this to the `develop` branches of front- and back-end.

Currently, there is no validation - I doubt, that it would be as easy as I imagined it, when I created https://github.com/HEnquist/pycamilladsp-plot/issues/10. So, I don't plan to implement this for now.

Feel free to reopen the ticket, if you find some bugs regarding this feature.

**Comment by HEnquist** [comment]
Alright! I'll try it as soon as I can. I'll merge this to master when I also merge the changes for camilladsp 1.0.0, hopefully quite soon.

**Comment by JWahle** [comment]
@HEnquist FYI I added a build step that runs python unit tests in https://github.com/HEnquist/camillagui-backend/commit/e9488b7973da6cb6d7b15dade7b5240edc49255d
