### ISSUE TITLE
Drag'n'drop for sorting items in the pipeline tab

### ISSUE THREAD

**Issue by JWahle** [HEnquist/camillagui#45]
Filters in the pipeline should be sortable via Drag'n'drop, since using the up/down buttons is cumbersome, when there are a lot of filters.

**Comment by JWahle** [comment]
@HEnquist I just pushed an implementation of this to `develop`.
For the time being, I decided to implement this only for filters of filter pipeline steps and not for individual channels or mixers in the pipeline. Also, DND doesn't work for mobile devices, so I left the up/down arrows. To remove them on desktop browsers, we would need a mobile detection and a manual way of switching between mobile and desktop per device - in case automatic detection fails.
![DND](https://user-images.githubusercontent.com/7657699/118509267-2d39ad80-b730-11eb-87eb-643ae696d990.png)

**Comment by HEnquist** [comment]
Nice! Works well. I don't think there is any need to hide the arrow buttons on desktops.
It would be neat to also be able to drag the Filter/Mixer steps around also, but I have no feeling for how much work that would be.

**Comment by JWahle** [comment]
I just pushed an implementation to `develop`. Please have a look.

**Comment by HEnquist** [comment]
Works just fine!
