### ISSUE TITLE
Switching to compact mode and back breaks logo and icon

### ISSUE THREAD

**Issue by HEnquist** [HEnquist/camillagui#60]
This only happens when running the gui served via the backend, not when using the node development server.
Normally the logo is loaded from ```http://localhost:5000/gui/static/media/camilladsp.95719842.svg```
After swithing to compact mode and back, it instead tries to load the logo from  ```http://localhost:5000/static/media/camilladsp.95719842.svg``` (note that "gui/" went missing).

This fiddling with the history seems a bit odd, can we do the switch differently?
https://github.com/HEnquist/camillagui/blob/master/src/compactview.tsx#L15

**Comment by HEnquist** [comment]
Fixed by https://github.com/HEnquist/camillagui/pull/61

**Comment by JWahle** [comment]
This fixes it for me.
