### ISSUE TITLE
Gain values in mixer are being rounded to integers

### ISSUE THREAD

**Issue by kbasaran** [HEnquist/camillagui#79]
I realized that if I create a config file I am able to use numbers with decimal points and they are also shown correctly in the GUI. But if I type in numbers with decimal points into the GUI, they will be rounded when I save to file.

**Comment by HEnquist** [comment]
Does it only happen for mixer gains, or are also Gain filters affected?

**Comment by HEnquist** [comment]
Ok thanks. I'll take a look.

**Comment by HEnquist** [comment]
fixed in 2.0
