### ISSUE TITLE
FR: Showing CPU load in GUI 

### ISSUE THREAD

**Issue by mike811** [HEnquist/camillagui#81]
Hello Henrik,

another feature request from my side:
It would be convenient if Camilla Gui would show CPU load similar to htop e.g.
And maybe some sort of visual warning in case e.g. to many IRs are used and one core is maxed out.

Thanks for this great sw.
Michael

**Comment by HEnquist** [comment]
Thanks for the reminder ;) I thought about adding this some time ago, and then forgot completely about it.
I added the needed bits in camilladsp here: https://github.com/HEnquist/camilladsp/commit/d0a6d8c75f9fe30056e4add0883ff0474ac0e28a
The gui for v2.0 will display this.

**Comment by mike811** [comment]
Great!
