### ISSUE TITLE
Mute is assigned only to first destination channel

### ISSUE THREAD

**Issue by volschin** [HEnquist/camillagui#82]
Using the Mute in the GUI only the first of two destination channels from a mixer is muted.
![IMG_4172](https://github.com/HEnquist/camillagui/assets/6284421/f0f0cbc4-3ae0-4418-8d5a-a6d4d2056755)

I think both (all) should be muted.

**Comment by HEnquist** [comment]
@volschin I'm closing this for now. If it's still relevant then please reopen and provide more details.
