### ISSUE TITLE
undefined instead of null?

### ISSUE THREAD

**Issue by JWahle** [HEnquist/camillagui#83]
I just noticed, that in the `next20` default values in configs are expressed through `null` values.
Have you considered using `undefined` instead?
Variables with value `undefined` will be omitted when serializing to JSON, so default values could be omitted from the config, when saved.
Also, it is a general recommendation to use only `undefined` in JavaScript/TypeScript and not use `null` - so just use one concept of nothingness and stick to it.

**Comment by HEnquist** [comment]
Yes I considered this. Things get complicated by the fact that json and yaml only have `null`. A missing value is deserialized to `undefined` in JS, but other deserializers may return something else. Camilladsp deserializes both missing values and `null` to the Rust value `None`. And when serializing all `None`s become `null`s.
Changing this is possible, but it means that the standard `Option` type in Rust can't be used, and requires writing a custom (de)serializer. Not very tempting!

**Comment by JWahle** [comment]
Ok, makes sense.
