### ISSUE TITLE
replace the fixed function Bass&Treble eq sliders with configurable controls

### ISSUE THREAD

**Issue by JWahle** [HEnquist/camillagui#93]
@HEnquist how do you envision this?

**Comment by HEnquist** [comment]
Now there are two sliders for two filters with fixed names, both controlling the gain parameter. The first thing that could be done is to allow the user to define their own sliders by giving the filter name, which parameter to control, and what range the slider should cover. That could be done in the gui config to start with.

Later improvements could be to allow defining them in the gui (supported by the backend via endpoints for storing and reading them)

**Comment by JWahle** [comment]
Sounds easy to do, I'll try something

**Comment by mike811** [comment]
Hello,

sounds great. I could use this to mix e.g. Front (left) with Surround (left) to generate Wide (left) and having some sort of pan control.

**Comment by JWahle** [comment]
I like the idea, but after thinking about this, it seems the best place for this UI Control configuration would be inside each CamillaDSP config - not all configs offer the same controls.
@HEnquist what do you think?

**Comment by HEnquist** [comment]
You mean that each config would somehow indicate what parameters should get a slider (and the range for it)? That could also be a way, but then it becomes a much larger project to build.
Sometimes it's likely better to keep this in the config. But then this needs to be added to every config. So sometimes, if most configs will have the same sliders anyway, it would be better to keep this separately.

I think that defining them in a single separate config is a pretty small effort, so in any case this is a good start. Then later on it could be expanded in all kinds of ways.

**Comment by HEnquist** [comment]
Looks great, I think this is perfect for now.
