### ISSUE TITLE
Compact view for filter blocks?

### ISSUE THREAD

**Issue by mike811** [HEnquist/camillagui#95]
Hello,

is there a trick to shrink the pipeline view when there are many filters involved? Example:
![IMG_1246](https://github.com/HEnquist/camillagui/assets/55871370/388adb67-64e9-445f-b928-b6c8492b3373)
Because this looks in the overview like this and it's hard to see anything:
![IMG_1245](https://github.com/HEnquist/camillagui/assets/55871370/211b3553-dcb6-48e9-8b07-18a882577485)

**Comment by HEnquist** [comment]
Yes there is a "collapse" button on the bottom of the plot. This collapses each Filter step to a single block.

**Comment by mike811** [comment]
Yes I'm aware of it but then the filter steps inside are not visible at all. I imagine something like displaying EQ_TTb_1-15 as one block.

**Comment by mike811** [comment]
And one more thing: Would it be possible to have different colors for the connecting arrows? With many channels it is hard to see where they go when many overlap.

**Comment by HEnquist** [comment]
> Yes I'm aware of it but then the filter steps inside are not visible at all. I imagine something like displaying EQ_TTb_1-15 as one block.

That's not possible and it's not planned. You could group filters that belong together in separate Filter steps as a workaround.



> And one more thing: Would it be possible to have different colors for the connecting arrows? With many channels it is hard to see where they go when many overlap.

I can try that. The color could be determined by the channel number that the arrow starts from

**Comment by mike811** [comment]
Question: "separate filter step" means FIR min phase? Or is there some other way implemented beside BiquadCombo/GraphicEqualizer?

**Comment by mike811** [comment]
What I tried: A seperate Mixer step for the IIR part. In compact view this looks almost right beside "large arrows":
![IMG_1247](https://github.com/HEnquist/camillagui/assets/55871370/f10995ed-6d3e-4b9d-899e-e0997051ed32)

**Comment by HEnquist** [comment]
No that's not what I meant, no need for extra mixers or FIR filters. Take the existing Filter step in the pipeline, and remove all the filters that are not called EQ-TT-something. Then add a second Filter step after and put those filters in that one instead.

**Comment by mike811** [comment]
Cool, this really works! :-)

**Comment by JWahle** [comment]
Nice, so this ticket can be closed?
