### ISSUE TITLE
Arrows are too large / different colors would be nice

### ISSUE THREAD

**Issue by mike811** [HEnquist/camillagui#96]
Hello,

in my large config lines and especially arrows are displayed way too large:
![IMG_1248](https://github.com/HEnquist/camillagui/assets/55871370/30fbdb07-7c9e-4dc8-8290-0634d7bbf9af)

Maybe we could we get rid of the arrows and just use simple (thin) lines?

**Comment by HEnquist** [comment]
The arrow size and line thickness should be automatically scaled to fit the rest. This has been on my list for a while.

**Comment by mike811** [comment]
Maybe we mention this line/arrow color change we talked about in the other issue here also as a reminder.
